### ISSUE TITLE
Error Please help

### ISSUE THREAD

**Issue by flexzuu** [ehamiter/get-on-the-bus#2]
I really love the idea of your programm but it does not work for me.

```bash
pi@raspberrypi ~/get-on-the-bus $ python alarm.py
Traceback (most recent call last):
  File "alarm.py", line 20, in <module>
    class Alarm():
  File "alarm.py", line 22, in Alarm
    flow = flow_from_clientsecrets(CLIENT_SECRET_FILE, scope='https://www.googleapis.com/auth/calendar', redirect_uri='http://localhost:8080/')
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 1343, in flow_from_clientsecrets
    client_type, client_info = clientsecrets.loadfile(filename, cache=cache)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/clientsecrets.py", line 145, in loadfile
    return _loadfile(filename)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/clientsecrets.py", line 108, in _loadfile
    return _validate_clientsecrets(obj)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/clientsecrets.py", line 81, in _validate_clientsecrets
    client_type))
oauth2client.clientsecrets.InvalidClientSecretsError: Missing property "redirect_uris" in a client type of "web".
```

I think i installed everthing right but maybe i have some issues with python install.
Please help me.

**Comment by flexzuu** [comment]
Hey i worked out the issue you need to generate a application json not a web one
